### PR TITLE
fix

### PR DESCRIPTION
**Pull request by ScreenTechnicals**

### CODE REVIEW

**Comment by ScreenTechnicals** [comment]
```diff
 Array.from({ length: 6 }).map(\n' +
        '        (_, index) =>\n' +
        '          // <GradientDivider\n' +
        '          //   key={index}\n' +
        '          //   className={twMerge(\n' +
        '          //     "!min-w-1",\n' +
        '          //     orientation === "vertical" && "rotate-90",\n' +
        '          //     className\n' +
        '          //   )}\n' +
        '          // />\n' +
        '          "hello"\n' +
        '      ),
```

**Comment by ScreenTechnicals** [comment]
```\n' +
        'diff\n' +
        '  //       return (\n' +
        '  //         <div\n' +
        '  //           key={step}\n' +
        '  //           className={twJoin(\n' +
        '  //             "flex items-center",\n' +
        '  //             orientation === "vertical" && "flex-col"\n' +
        '  //           )}\n' +
        '  //         >\n' +
        '  //           {/* {steps.length > 4 && isLastStep && (\n' +
        '  //             <DashedDivider orientation={orientation} className={divider} />\n' +
        '  //           )} */}\n' +
        '  //           {shouldShowSteps && (\n' +
        '  //             <StepItem\n' +
        '  //               step={{ step, ...restStepProps }}\n' +
        '  //               isSelected={step === selectedStep}\n' +
        '  //               classNames={restClassName}\n' +
        '  //               hideLabel={hideLabel}\n' +
        '  //             />\n' +
        '  //           )}\n' +
        '  //           {selectedStep === step && selectedStep > 2 && (\n' +
        '  //             <StepItem\n' +
        '  //               step={{ step, ...restStepProps }}\n' +
        '  //               isSelected={step === selectedStep}\n' +
        '  //               classNames={restClassName}\n' +
        '  //               hideLabel={hideLabel}\n' +
        '  //             />\n' +
        '  //           )}\n' +
        '  //           {/* {shouldShowDivider && (\n' +
        '  //             <GradientDivider orientation={orientation} className={divider} />\n' +
        '  //           )} */}\n' +
        '  //         </div>\n' +
        '  //       );\n' +
        '  //     }),\n' +
        '  //   [steps, selectedStep, orientation, divider, restClassName, hideLabel]\n' +
        '  // );\n' +
        '        orientation === "vertical" ? "items-start" : "flex-col",\n' +
        '```\n

**Comment by meness** [comment]
from now on

**Comment by ScreenTechnicals** [comment]
test

**Comment by ScreenTechnicals** [comment]
test

**Comment by ScreenTechnicals** [comment]
sxsxs

**Comment by ScreenTechnicals** [comment]
```diff
+ dcd
- dkd 
```

**Comment by ScreenTechnicals** [comment]
gegee

**Comment by ScreenTechnicals** [comment]
xwx

**Comment by ScreenTechnicals** [comment]
cscs

**Comment by ScreenTechnicals** [comment]
11:02

**Comment by ScreenTechnicals** [comment]
11:14

**Pull request closed without merging**
